### ISSUE TITLE
single flaw

### ISSUE THREAD

**Issue by damirqa-work** [edenroseFR/Web-based-SSIS#66]
there should be PHOTO_UPLOAD
https://github.com/edenroseFR/Web-based-SSIS/blob/3553dc33defdcade0f207e200efbeceec0b46a2a/ssis/views/students/utils.py#L102

**Comment by edenroseFR** [comment]
Hi @damirqa-work, can I assign you to do this?

**Comment by edenroseFR** [comment]
@damirqa-work  -- if you want to, you can send a PR to the develop branch. Thanks!
